# -*- coding: utf-8 -*-
"""ML-ASS17-2403A52010

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtxQzd-A5HRB86Tn8KkDMOYuHC8ljfUX
"""

# Encode the 'diagnosis' column (M=1, B=0)
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

# Display the first 5 rows with the encoded diagnosis and value counts to verify
display(df.head())
display(df['diagnosis'].value_counts())

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
# Drop 'id' and 'Unnamed: 32' columns if they exist as they are likely not features
X = df.drop(columns=['id', 'diagnosis', 'Unnamed: 32'], errors='ignore')
y = df['diagnosis']

# Split the dataset into training and testing sets (80/20 ratio)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Display the shapes of the resulting sets
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

from sklearn.tree import DecisionTreeClassifier

# Define the max_depth values to experiment with
max_depth_values = [3, 5, 7, 10]

# Dictionary to store trained models
decision_tree_models = {}

print("Training Decision Tree Classifiers with varying max_depth values:")
for depth in max_depth_values:
    # Initialize Decision Tree Classifier with the current max_depth
    dt_classifier = DecisionTreeClassifier(max_depth=depth, random_state=42)

    # Train the model
    dt_classifier.fit(X_train, y_train)

    # Store the trained model
    decision_tree_models[f'max_depth_{depth}'] = dt_classifier

    print(f"  - Decision Tree Classifier trained with max_depth={depth}")

print("\nAll Decision Tree Classifiers trained.")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Evaluating Decision Tree Classifiers:")

for name, model in decision_tree_models.items():
    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print(f"\n--- Model: {name} ---")
    print(f"  Accuracy: {accuracy:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall: {recall:.4f}")
    print(f"  F1-Score: {f1:.4f}")

print("\nAll models evaluated.")